export const CHANGE_LOCALE = 'CHANGE_LOCALE';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const HIDE_DIALOG = 'HIDE_DIALOG';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';

export const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';

export const SET_AUTHENTICATION_TOKEN = 'SET_AUTHENTICATION_TOKEN';
export const UNSET_AUTHENTICATION_TOKEN = 'UNSET_AUTHENTICATION_TOKEN';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSE_DETAILS = 'FETCH_COURSE_DETAILS';
